apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: argocd
type: Opaque
data:
  aws_access_key_id: QUtJQVNGVUlSWUQ0QTVFQTdaVk0K
  aws_secret_access_key:  aVY5QVgxL243OGZpM1Y0cG5ydUM0OUVVN0ttaUFEU2VPT1VGYzljMgo=
