apiVersion: v1
kind: Service
metadata:
  name: python-flask-service
spec:
  selector:
    app: python-flask-app
  ports:
    - protocol: TCP
      port: 80  # Exposing port 80 for the service
      targetPort: 5000  # The internal port the Flask app listens on
  type: ClusterIP  # This will expose the service externally (if supported by your cloud provider)
