apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  annotations:
    argocd-image-updater.argoproj.io/image-1: "149536489720.dkr.ecr.us-east-2.amazonaws.com/python-flask-app"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
